### ISSUE TITLE
Infection total_infected

### ISSUE THREAD

**Issue by JanosAudron** [kidpixo/COVID19-dashboard#1]
Cosa significa il grafico "Infection total_infected"?

**Comment by kidpixo** [comment]
É il terzo parametro della funzione descritto cosí :
```
c: 134866.39± 4244.27 : the total number of recorded infected people at the infection’s end
```

**Comment by kidpixo** [comment]
Devo scrivere una documentazione piú accurata sulla pagina iniziale di quello che ho fatto effettivamente.
